version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:6002
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Persist the SQLite database
    ports:
      - "6002:6002"
